# Generated by Django 5.1.3 on 2024-11-10 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0003_countryinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countryinfo',
            name='popDensity',
            field=models.FloatField(),
        ),
    ]
